from . import foot_nonfoot_wise_wizard
from . import inventory_stock_report_wizard
from . import for_test_print_excel_report_wizard
from . import mobile_data_wizard
from . import send_received_report_wizard
from . import inventory_stock_report_datewise_wizard
from . import all_current_stock_barcode_wizard
from . import point_report_wizard
from . import account_payment_transaction_report_wizard
from . import account_payment_support_report_wizard
from . import daily_sales_datewise_wizard
from . import recap_shop_report_wizard